name: Multi-Platform Docker Build

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NEXTAUTH_URL=${{ env.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            BLOB_READ_WRITE_TOKEN=${{ secrets.BLOB_READ_WRITE_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbotapi-chatbotfront:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 停止並移除舊的容器（如果存在）
            docker stop chatbotapi-chatbotfront-container || true
            docker rm chatbotapi-chatbotfront-container || true
            
            # 拉取最新的映像檔
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chatbotapi-chatbotfront:latest
            
            # 運行新的容器
            docker run -d \
              --name chatbotapi-chatbotfront-container \
              -p 3000:3000 \
              -e NEXTAUTH_URL=http://${{ secrets.EC2_HOST }}:3000 \
              -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              -e BLOB_READ_WRITE_TOKEN=${{ secrets.BLOB_READ_WRITE_TOKEN }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/chatbotapi-chatbotfront:latest
